### ISSUE TITLE
Backend-URL in Plugin-Frontend konfigurieren

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/plugin-template#12]
Lösungsansatz über Angular env

**Comment by profiluefter** [comment]
keat evaluiert obs hihaut, theoretisch is' implementiert

**Comment by CallMeAlasca** [comment]
is reviewed, is auf 4 Repos oda so aufteilt, haut hie laut Gurtner & Klause (Reviewer)
